enable_learning_status:
  description: "Enable the learning status."
  fields:
    state:
      description: "State to set the learning status."
      example: true

get_learned_ir_code:
  description: "Get the learned IR code."
  fields:
    learning_time:
      description: "Learning time to fetch the IR code."
      example: 5

save_learned_ir_code:
  description: "Save the learned IR code."
  fields:
    category_id:
      description: "Category ID."
      example: 2
    remote_name:
      description: "Remote name."
      example: "MyRemote"
    key_name:
      description: "Key name."
      example: "Power"
    learned_code:
      description: "Learned code."
      example: "code123"

get_remote_keys:
  description: "Get keys of a remote control."
  fields:
    infrared_id:
      description: "Infrared device ID."
      example: "vdevo15345926009****"
    remote_id:
      description: "Remote control ID."
      example: "d5s65ca55"

send_standard_command:
  description: "Send standard command to control the specified device."
  fields:
    infrared_id:
      description: "Infrared device ID."
      example: "vdevo15345926009****"
    remote_id:
      description: "Remote control ID."
      example: "d5s65ca55"
    category_id:
      description: "Category ID."
      example: 2
    remote_index:
      description: "Remote index."
      example: 147
    key:
      description: "Key."
      example: "Power"

send_key_command:
  description: "Send key command to control the specified device."
  fields:
    infrared_id:
      description: "Infrared device ID."
      example: "vdevo15345926009****"
    remote_id:
      description: "Remote control ID."
      example: "d5s65ca55"
    category_id:
      description: "Category ID."
      example: 2
    key_id:
      description: "Key ID."
      example: 1
    key:
      description: "Key."
      example: "power"
